services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: restart
          path: ./backend/src/
    command: uvicorn main:fastapi_app --host 0.0.0.0 --port 8000 
    env_file:
      - .env 
    depends_on:
      - db_service

  db_service:
    image: postgres:17.5
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env

  streamlit:
    build:
      context: ./backend
      dockerfile: streamlit.Dockerfile
    network_mode: host  
    command: streamlit run src/streamlit.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - 8501:8501
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - backend

  # static_html:
  #   build:
  #     context: ./static_html
  #     dockerfile: static.Dockerfile
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./static_html/src:/app
  #   command: python -m http.server 8000


volumes:
  db_data: